apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: fpem25pxp-python 
  janus-idp.io/tekton: fpem25pxp-python
  backstage.io/kubernetes-id: fpem25pxp-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: fpem25pxp-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml