apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: fpem25pxp-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: fpem25pxp-python 
  name: fpem25pxp-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: fpem25pxp-python 
